// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/pose3d-demo.vue:11-16,56-61
// Pattern: tab

import { expect, test } from '@playwright/test'

// three.js 要 WebGL；headless Chromium 預設拿不到 GPU，用 SwiftShader 走軟體渲染
// 補上（同 scripts/capture-previews.mjs）。
test.use({
  launchOptions: {
    args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
  },
})

// 軟體渲染 + 0.7MB 樣本載入，給足時間
test.setTimeout(120_000)

// canvas 上的 data-engine 由 three.js 自己掛（"three.js r185"），拿它辨認
// 當下掛載的是不是 Three.js 版渲染器。
const THREE_CANVAS = 'canvas[data-engine^="three.js"]'

test.describe('vibe：pose3d-demo 骨架渲染器分頁', () => {
  test('新增的「骨架（Plotly 對照）」分頁可切換，且與 Three.js 版互斥', async ({ page }) => {
    await page.goto('/pose3d-demo')

    const three = page.getByRole('tab', { name: '骨架（Three.js）' })
    const plotly = page.getByRole('tab', { name: '骨架（Plotly 對照）' })
    const threeCanvas = page.locator(THREE_CANVAS)

    await expect(three).toBeVisible({ timeout: 45_000 })
    await expect(plotly).toBeVisible()

    await three.click()
    await expect(three).toHaveAttribute('aria-selected', 'true')
    // 首次進站要等 dev server 編譯 + 0.7MB 樣本載入才畫得出來，時間放寬
    await expect(threeCanvas).toBeVisible({ timeout: 45_000 })

    // 切到對照版：Three.js 場景要被卸掉，兩版不會同時掛著
    await plotly.click()
    await expect(plotly).toHaveAttribute('aria-selected', 'true')
    await expect(threeCanvas).toHaveCount(0)

    // 切回來要能重新掛起（卸載沒把 host 弄壞）
    await three.click()
    await expect(three).toHaveAttribute('aria-selected', 'true')
    await expect(threeCanvas).toBeVisible()
  })
})
