// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/components/modules/PitchPoseShowcase.vue:11-17,36-41,53-61
// Pattern: conditional-render

import { expect, test } from '@playwright/test'

// three.js 要 WebGL；headless Chromium 預設拿不到 GPU，用 SwiftShader 補上
test.use({
  launchOptions: {
    args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
  },
})

test.setTimeout(120_000)

// data-engine 由 three.js 自己掛在 canvas 上，用來辨認 Three.js 版是否掛載中
const THREE_CANVAS = 'canvas[data-engine^="three.js"]'

test.describe('vibe：pitch-pose-skeleton 模組頁渲染器切換', () => {
  test('選單切到「Plotly 對照」會卸掉 Three.js 版，切回來能重新掛起', async ({ page }) => {
    await page.goto('/modules/pitch-pose-skeleton')

    const renderer = page.getByRole('combobox', { name: '渲染器' })
    const threeCanvas = page.locator(THREE_CANVAS)

    // 預設 Three.js。首次進站要等 dev server 編譯 + 樣本載入才畫得出來，時間放寬
    await expect(renderer).toBeVisible({ timeout: 45_000 })
    await expect(threeCanvas).toBeVisible({ timeout: 45_000 })

    await renderer.click()
    await page.getByRole('option', { name: 'Plotly 對照' }).click()
    await expect(renderer).toHaveText(/Plotly 對照/)
    await expect(threeCanvas).toHaveCount(0)

    await renderer.click()
    await page.getByRole('option', { name: 'Three.js' }).click()
    await expect(renderer).toHaveText(/Three\.js/)
    await expect(threeCanvas).toBeVisible()
  })
})
