// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/pages/pitch3d-demo.vue:23-27,41-44,79-88
// Pattern: conditional-render

import { expect, test } from '@playwright/test'

test.use({
  launchOptions: {
    args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
  },
})

test.setTimeout(120_000)

test.describe('vibe：pitch3d-demo 渲染器切換', () => {
  // TODO: [no-locator] 這頁的渲染器 USelect 沒有 aria-label，與同列的縮放 USelect
  // 都是無名 combobox，靠 role + name 分不出來（用 .first() 只是綁 DOM 順序，改版即碎）。
  // 解除方式：比照 PitchPoseShowcase.vue／PitchTrajectoryShowcase.vue，
  // 在 app/pages/pitch3d-demo.vue 的渲染器 USelect 補 aria-label="渲染器"，再重跑 /vibe-e2e。
  test.skip('選單切到「Plotly 對照」會換掉渲染器', async ({ page }) => {
    await page.goto('/pitch3d-demo')

    const renderer = page.getByRole('combobox', { name: '渲染器' })
    const plotlyPlot = page.locator('.js-plotly-plot')

    await expect(plotlyPlot).toHaveCount(0)
    await renderer.click()
    await page.getByRole('option', { name: 'Plotly 對照' }).click()
    await expect(plotlyPlot).toBeVisible({ timeout: 60_000 })
  })
})
