import type { ModuleSpec } from './types'
import { defineAsyncComponent } from 'vue'

// 全部 3D 研究模組的登錄表。索引頁與展示頁都讀這裡。
// done  = 研究告一段落（目前 11 個模組全部在此狀態）
// wip   = 有可運作實作可點進去看，但還在調整
// planned = 尚未動工，四個必備區塊先給文字輪廓、參考資料選填

export const modules: ModuleSpec[] = [
  {
    slug: 'baseball-spin',
    title: '棒球轉軸視覺化',
    sport: 'baseball',
    status: 'done',
    category: 'ball',
    summary: '吃演算法後端的 result.json，用 Three.js 重現該球真實旋轉（含縫線樣貌），並疊上依 spin_tilt 旋轉的轉軸指針。',
    tags: ['Three.js', 'spin-axis', 'glTF'],
    updated: '2026-07',
    demoRoute: '/spin-demo',
    presentation: defineAsyncComponent(() => import('~/components/modules/BaseballSpinShowcase.vue')),
    tech: [
      'Three.js（raw，正交相機）',
      'glTF 模型載入（GLTFLoader）',
      'Zod 資料驗證',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'clock-spin',
    title: '時鐘轉軸',
    sport: 'baseball',
    status: 'done',
    category: 'ball',
    summary: '把 spin_tilt 以 2D 時鐘面板呈現：盤面靜態、指針整組 rotate(spin_tilt.degrees)。與 baseball-spin 的 3D 指針是同一份資料的兩種呈現。',
    tags: ['SVG', '2D', 'spin-tilt'],
    updated: '2026-07',
    demoRoute: '/clock-demo',
    presentation: defineAsyncComponent(() => import('~/components/modules/ClockSpinShowcase.vue')),
    tech: [
      '純 SVG（無 3D 函式庫、無圖檔）',
      '12 點盤面幾何（12 點在正上方＝角度 −90°）',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'pitch-pose-skeleton',
    title: '投球姿態 3D 骨架',
    sport: 'baseball',
    status: 'done',
    category: 'pitcher',
    summary: '把多鏡位重建的 COCO-17 骨架逐幀播放，用 Three.js 畫點線圖；軸範圍固定，播放中空間不會跟著資料「呼吸」，且播放與視角操作天生解耦——拖曳旋轉不會被每秒 60 次的重繪打斷。',
    tags: ['Three.js', 'pose', 'skeleton', 'COCO-17'],
    updated: '2026-08',
    demoRoute: '/pose3d-demo',
    presentation: defineAsyncComponent(() => import('~/components/modules/PitchPoseSkeletonShowcase.vue')),
    tech: [
      'Three.js（Line2 骨頭 + InstancedMesh 關節 + 自繪 3D 軸盒）',
      'COCO-17 骨架拓樸（19 條骨頭）',
      'rAF 播放時鐘（0.05–1× 可調）',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'pitch-pose-human',
    title: '投球姿態 3D 真人模型',
    sport: 'baseball',
    status: 'done',
    category: 'pitcher',
    summary: '同一份 COCO-17 骨架，改用 three.js 把 keypoints retarget 到人形 glTF 模型驅動骨骼。目前是可運作的初版：手腕、脊椎等 COCO-17 沒有的關節為近似值，three.js 路線仍在研究調整中。另可切換為程式生成素體（keypoints 直接組幾何、無 retarget 近似），兩者都能疊上骨架看關節對應的身體部位。',
    tags: ['Three.js', 'pose', 'retarget', 'glTF'],
    updated: '2026-08',
    demoRoute: '/pose3d-demo',
    presentation: defineAsyncComponent(() => import('~/components/modules/PitchPoseHumanShowcase.vue')),
    tech: [
      'Three.js（GLTFLoader、OrbitControls、Quaternion retarget）',
      'Xbot.glb（three.js 官方範例人形骨架）',
      '骨長校正（依資料量到的骨長拉伸骨架，每位選手自動適配）',
      '程式生成素體（圓柱四肢＋關節球＋定向橢球軀幹，不載模型檔）',
      '骨架疊顯（x-ray，關閉 depthTest）',
      '缺測 keypoint 線性補值',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'batter-pose-skeleton',
    title: '打擊姿態 3D 骨架',
    sport: 'baseball',
    status: 'done',
    category: 'batter',
    summary: '把 BPE 揮棒結果的 19 點骨架（COCO-17 人體＋球棒兩端）逐幀播放：細線分析骨架（像專業動作分析軟體：細線加小顆關節亮點）、四肢左右分色，球棒照真實木棒的輪廓與木紋畫出，球用專案的 3D 棒球模型帶出 20 顆由細到粗的拖尾。以擊球為中心：載入時停在擊球幀、時間顯示「距擊球幾毫秒」，畫布上直接看得到棒速、攻擊角、啟動到擊球時間。可逐幀調整（±1、±10、輸入幀數、鍵盤），切換全景、打者特寫、側面、投手方向、俯視與深淺兩套配色；座標與擊球點九宮格、預測落點球場圖同一套，原點都是本壘板尖端。',
    tags: ['Three.js', 'pose', 'skeleton', 'batting', 'BPE'],
    updated: '2026-09',
    presentation: defineAsyncComponent(() => import('~/components/modules/BatterPoseSkeletonShowcase.vue')),
    tech: [
      'Three.js（沿用 scene3d 的 Viewport 與 hover 標籤；骨架寫法同 pitch-pose）',
      'BPE 座標直接當世界座標：scene3d 相機本來就 z-up，規範給的 three.js y-up 換算式用不到',
      '骨架拓樸不寫死：一律讀檔內 joint_names 與 bones，球棒以名稱 bat_* 判定；左右半身、頭部也只看名稱分類',
      '細線分析骨架（同參考實作的風格）：骨頭是固定 3px 的細線（LineSegments2，頭部 1.75px），在每個視角與縮放下都一樣俐落；關節是半徑 2.3 cm 的霧面小亮點（InstancedMesh ＋ MeshLambertMaterial）。四肢左右分色、軀幹中性、頭部細而淡',
      '球棒照標準木棒輪廓做成旋轉體（LatheGeometry：握把尾端圓頭、細握把、漸粗過渡、打擊區、圓弧棒頭），木紋貼圖（固定種子，每次一樣）＋亮光漆（MeshPhysicalMaterial clearcoat）＋環境反射（RoomEnvironment），握把包深色握把布',
      '深淺兩套畫布配色集中在 core/swingTheme.ts，場景與圖例共用同一份；背景是漸層、地面有微光，不是純黑純白',
      '球用 baseball-spin 同一顆棒球模型（GLTFLoader，歸一化成單位球後複製 20 份、幾何共用、材質逐顆複製以各自設透明度）；沒給模型或載入失敗時退回規範的紅球',
      '場景參照物照參考實作：不透明白色本壘板、只畫在地面的格線（每格 20 cm，本壘板周圍 3 m 內、往外漸層淡出）、指向投手的箭頭',
      '球體拖尾固定 20 顆物件池：第 age 顆取目前幀往前第 age 幀的球，缺值就隱藏，不往更早的幀找補',
      '拖尾只由目標幀決定、不累積歷史，所以播放、拖曳、逐幀、循環、換事件都不會殘影',
      '取景依點本身、不框方盒的空角落，注視點挪到投影範圍中心：全景照規範框住整段動作的關節與球，打者特寫只框人體；播放中不重算，空間不會「呼吸」',
      '五個視角一鍵切換：全景（預設）、打者特寫、側面（一壘側平視，看跨步與球棒高低）、投手方向、俯視（看相對本壘板的位置）；點目前這一顆就是重設視角',
      '擊球標籤、操作提示、視角切換、圖例都疊在畫布上，出現或消失都不會推動控制列',
      '播放時鐘以 time_s 對齊（二分搜尋查幀），預設 0.25×；載入與換事件時一律停在擊球幀、不自動播放（先看懂這一下在哪裡碰到球，也滿足規範的減少動態效果）',
      '擊球是整個介面的視覺中心：畫布標籤、時間軸刻度「擊球」、跳至擊球按鈕、相對時間的 0 ms 都用琥珀色；時間軸下方顯示「距擊球 −120 ms／擊球 0 ms／擊球後 +80 ms」',
      '本次揮棒三項核心數據（棒速、攻擊角、啟動到擊球時間）疊在畫布右上角，也放大成主卡片；其餘三項放次層。卡片一位小數、秒改毫秒，原始值與欄位名稱在提示裡',
      '逐幀：±1、±10 按鈕與幀數輸入框都走播放時鐘的 step／seek（會先暫停）；鍵盤 ← → 逐幀、Shift 一次 10 幀、空白鍵播放暫停，焦點在輸入框、時間軸、選單上時讓給元件自己處理',
      '場景 class 框架無關，Vue 元件只是薄殼；three 在 onMounted 才動態載入，卸載期間不留 WebGL context',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'contact-point-grid',
    title: '擊球點九宮格',
    sport: 'baseball',
    status: 'done',
    category: 'batter',
    summary: '把 BPE 揮棒結果的擊球點（球棒碰到球的位置）以捕手視角畫在好球帶九宮格上，看偏左右多少、多高。全部事件的擊球點疊在同一張圖上（選中的高亮、其他淡灰可點選切換），好球帶由打者級別推算；視野固定 150 × 200 cm，超出視野的點照座標擴大顯示、不裁切。可切換簡約呈現：聚焦好球帶，改畫本壘板與打擊區示意。',
    tags: ['SVG', '2D', 'contact', 'BPE'],
    updated: '2026-09',
    presentation: defineAsyncComponent(() => import('~/components/modules/ContactPointGridShowcase.vue')),
    tech: [
      '純 SVG（無 3D 函式庫、無圖表庫）',
      'SVG 單位 = 1 cm：橫縱天然等比例，擊球點半徑就是真實球半徑 3.65 cm',
      '捕手視角 +x 在右——與 strike-zone-grid 刻意反轉 x 軸的畫法相反，因為 BPE 規範明定',
      '只用 point_cm 的 x 與 z，y 不使用（等於把九宮格平面移到擊球點所在深度）',
      '好球帶共用 baseball-field 的打者級別推算，與九宮格落點圖同一套規則',
      '固定視野 x ±75、z 0–200 cm：23 筆全裝得下；超界才擴大，不 clamp',
      '簡約呈現：視野縮到 x ±48、z −30 cm～好球帶上緣 +15 cm，拿掉刻度與點旁標籤，改畫本壘板五角形與打擊區示意；成棒時 5 筆擊球點會觸發擴大',
      '不依「在不在好球帶內」換色——擊球點不是好壞球判定；格號 1～9 淡淡標在格子正中，只標位置',
      '其他事件疊圖：讀 overview.json（23 筆拿掉骨架與動畫，約 33KB），每筆照樣過檢查關卡；灰點不讓視野擴大',
      '字級與點的點擊範圍保證最小像素（ResizeObserver 量實際寬度換算回 SVG 單位）：手機窄欄裡字不會縮到讀不了',
      '元件只吃 x／z 數字、不依賴 BPE 格式；檢查關卡與缺值規則在共用資料層 bpe-data',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'landing-field-chart',
    title: '預測落點球場圖',
    sport: 'baseball',
    status: 'done',
    category: 'batter',
    summary: '查看本次擊球的預測落點、飛行距離與方向。透過事件選單或左右箭頭切換揮棒紀錄，球場會依落點位置自動調整視野。',
    tags: ['SVG', '2D', 'spray-chart', 'BPE'],
    updated: '2026-09',
    presentation: defineAsyncComponent(() => import('~/components/modules/LandingFieldChartShowcase.vue')),
    tech: [
      '純 SVG（無圖表庫）',
      'SVG 單位 = 1 m：predicted_landing_point_m 是 payload 唯一的公尺欄位，直接當座標、不換算',
      '界外線 y = |x|、外野弧 y = 44.912 + √(77.088² − x²)，兩者在 (±72.125, 72.125) 相接',
      '外野弧用折線不用 SVG arc：翻轉 y 軸後 sweep-flag 不直覺，折線共用同一個座標轉換不會算錯',
      '草地、紅土內野、壘包與打擊區提供場地參考；距離弧與內野細節可關閉',
      '固定視野 x ±94、y −30–142 m，包含界外草地；落點超出才擴大（23 筆只有事件 #11 會觸發），不 clamp',
      '落點旁用白底資訊卡顯示距離與方向（「56.3 m／一壘側 2.9°」），原始座標放滑鼠提示；資訊卡自動避開視野邊緣',
      '字級與點的點擊範圍保證最小像素（ResizeObserver 量實際寬度換算回 SVG 單位）：手機上整張圖只剩兩百多像素寬，字不會縮到約 6px',
      '元件只吃 x／y 數字、不依賴 BPE 格式；檢查關卡與缺值規則在共用資料層 bpe-data',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'pitch-trajectory',
    title: '來球 3D 軌跡圖',
    sport: 'baseball',
    status: 'done',
    category: 'ball',
    summary: '用 Three.js 在同一個 3D 場景畫出投球軌跡、本壘板實體與好球帶九宮格；採暗色主題，世界單位直接是 cm，1cm 在三軸的視覺長度天生一致、空間不變形。',
    tags: ['Three.js', 'trajectory', '3D', 'strike-zone'],
    updated: '2026-08',
    demoRoute: '/pitch3d-demo',
    presentation: defineAsyncComponent(() => import('~/components/modules/PitchTrajectoryShowcase.vue')),
    tech: [
      'Three.js（Line2 軌跡與九宮格 + BufferGeometry 本壘板 + 自繪 3D 軸盒）',
      '暗色主題（黑底 + 琥珀黃軌跡）',
      '本壘板五邊形自動生成側面與底面',
      '世界單位即 cm（不需 Plotly 那套 aspectratio 人工換算）',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'strike-zone-grid',
    title: '九宮格落點圖',
    sport: 'baseball',
    status: 'done',
    category: 'ball',
    summary: '把入壘點投影到好球帶九宮格的純 SVG 呈現，含好壞球幾何判定與本壘板、打擊區的透視底座；縮放為真實比例等比換算，不會把好球帶畫扁。',
    tags: ['SVG', 'strike-zone', '2D', '好壞球判定'],
    updated: '2026-07',
    demoRoute: '/bt3d-demo',
    presentation: defineAsyncComponent(() => import('~/components/modules/StrikeZoneGridShowcase.vue')),
    tech: [
      '純 SVG（無 3D 函式庫）',
      '好球帶比例：上緣 = 身高 × 0.535、下緣 × 0.27（對齊後端）',
      '九宮格分格判定 classifyCell',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'pitch-distribution',
    title: '落點分布圖',
    sport: 'baseball',
    status: 'done',
    category: 'ball',
    summary: '一批投球在好球帶上的分布：九宮格熱區看集中在哪，散點疊圖看實際散布與框外的球，可依投手與球種篩選。與九宮格落點圖的分工是「這批球」對「這一球」。',
    tags: ['SVG', 'heatmap', 'distribution', '2D'],
    updated: '2026-07',
    presentation: defineAsyncComponent(() => import('~/components/modules/PitchDistributionShowcase.vue')),
    tech: [
      '純 SVG（無 3D 函式庫、無圖表庫）',
      '同色散點合併成單一 path：600 顆點只有 2 個 DOM 節點',
      'fill-opacity 疊出密度，不必算 KDE',
      '座標直接用 cm，SVG 單位 = 1cm 故天然等比例',
      'Vue 3 / Nuxt 4',
    ],
  },
  {
    slug: 'pose-metrics-chart',
    title: '投手姿態數據線性圖',
    sport: 'baseball',
    status: 'done',
    category: 'pitcher',
    summary: '把單球的七條姿態角度疊在同一條 ±180 的角度軸上，橫軸為影格序號，配上抬腿／踏地／出手三條事件線，看動作鏈上各關節什麼時候到頂。三機影片接在圖上方共用同一個播放頭：播影片游標跟著走，拖圖表影片跟著跳。圖例可逐條點掉單獨看。',
    tags: ['SVG', 'line-chart', 'biomech', 'multi-series', 'video-sync'],
    updated: '2026-08',
    presentation: defineAsyncComponent(() => import('~/components/modules/PoseMetricsChartShowcase.vue')),
    tech: [
      '純 SVG 折線（無圖表庫：不裝 chart.js／plotly）',
      '兩種版面：分列（預設，各自最佳值域）與疊圖（共用 ±180 軸，看得到交叉點）',
      '分列解決的是壓扁——疊圖時軀幹前傾只用到軸高的 16%、肩膀內旋 25%',
      '一條指標一個 path、748 個點只有 1 個 DOM 節點',
      '缺口雙門檻：≤10 格且兩端角度差 ≤15 度才接起來，其餘留白不猜',
      '±180 環繞角以相鄰差 > 180 判定並斷線，不畫貫穿全圖的假垂直線',
      'X 軸是影格序號（約 250fps，取樣不等距，實測相鄰間隔 0.6～9.0 ms）',
      '平滑分兩層：Catmull-Rom 只改點與點怎麼連（點不動），高斯低通才動數值',
      '高斯逐段濾波，段落端點用反對稱延拓——截短窗口會把端點往內拉 0.9 度',
      '缺口門檻與濾波強度不寫死：每次拿到資料重新推導（fps、缺口分布、事件間隔）',
      'Y 軸用角度的自然分度（45 一格），通用 1／2／5 階梯會給出 100 度這種刻度',
      '深淺兩套完整配色（theme prop，預設 light）：深底用 200–300 色階、白底換 500–600',
      '七色的色相在環上拉開（紅／橘／黃／綠／藍／紫／洋紅）；圖表與圖例共讀 core/palette.ts',
      '拖曳游標讀值：面板列出當下影格的各項數值（小數一位），塞不下就翻到游標另一側',
      '游標位置走 defineModel，父層綁 v-model 就能拿去驅動別的畫面',
      '三機影片與曲線共用播放頭：影片第 N 格就是 timeseries[N]，靠影格序號對位不靠秒數',
      '播放時 rAF 只讀主畫面的 currentTime、不逐格 seek；跟隨機位漂超過 0.12 秒才校正',
      '切主畫面只換格線位置不搬 DOM——搬容器會讓 video 重新掛載、整支影片重載',
      'Vue 3 / Nuxt 4',
    ],
  },
]

export function findModule(slug: string): ModuleSpec | undefined {
  return modules.find(m => m.slug === slug)
}
