// AUTO-GENERATED by /vibe-e2e — edit via regenerate（/vibe-e2e 同來源覆蓋）
// Source hunk: app/components/modules/PitchPoseShowcase.vue:36-41
// Pattern: conditional-render

/**
 * 放 unstable/（不進守門）的原因不是時序敏感，而是**環境限制**：
 *
 * Vite 7 的 dev server 轉換 7.4MB 的 `plotly.js-dist-min` 預打包檔會
 * "Maximum call stack size exceeded"，該檔以 404 回應（同目錄 1.6MB 的 three.js 正常 200），
 * 於是 Plotly 對照版的 dynamic import 必定失敗。與本次渲染器遷移無關——
 * 遷移前後 import 寫法相同，只是換了資料夾。
 *
 * 因此本 spec 只在**非 dev server** 的環境下才驗得過：
 *   npm run generate && npx nuxi preview --port 4173
 *   E2E_BASE_URL=http://localhost:4173 npx playwright test --config playwright.vibe.config.ts unstable/
 *
 * 若之後 dev 端修好（例如 nuxt.config 加 vite.optimizeDeps 對策），把本檔搬回上層即可進守門。
 */

import { expect, test } from '@playwright/test'

test.use({
  launchOptions: {
    args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'],
  },
})

test.setTimeout(120_000)

test.describe('vibe：pitch-pose-skeleton Plotly 對照版實際渲染', () => {
  test('切到「Plotly 對照」會畫出 Plotly 圖', async ({ page }) => {
    await page.goto('/modules/pitch-pose-skeleton')

    const renderer = page.getByRole('combobox', { name: '渲染器' })
    // Plotly 掛載後會在容器加上這個 class
    const plotlyPlot = page.locator('.js-plotly-plot')

    await expect(renderer).toBeVisible()
    await expect(plotlyPlot).toHaveCount(0)

    await renderer.click()
    await page.getByRole('option', { name: 'Plotly 對照' }).click()
    await expect(plotlyPlot).toBeVisible({ timeout: 60_000 })
  })
})
