/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 服務健康檢查
         * @description 回報服務存活狀態與檢查時間，供部署探針與監控使用。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 服務正常 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /**
                                 * @description 存活訊號，恆為 ok（Redis 故障時服務仍持續供應、ingestion 走降級， 不因 Redis 翻轉本欄位）。
                                 * @example ok
                                 */
                                serviceStatus: string;
                                /**
                                 * @description Redis 連線探測結果（1 秒 ping 上限）：ok 正常、down 故障或逾時、 not_configured 未配置（in-memory/dev 模式）。
                                 * @example ok
                                 * @enum {string}
                                 */
                                redis: "ok" | "down" | "not_configured";
                                /** Format: date-time */
                                checkedAt: string;
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 帳號登入
         * @description 使用帳號與密碼進行登入，回傳短效 access token（JWT）與長效 refresh token （opaque 隨機字串，非 JWT）。refresh token 僅能用於 /api/v1/auth/refresh 的 request body，嚴禁出現在任何 query 參數。此 API 錯誤訊息統一以降低帳號列舉攻擊風險。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example super_admin */
                        account: string;
                        /**
                         * Format: password
                         * @example password123
                         */
                        password: string;
                    };
                };
            };
            responses: {
                /** @description 登入成功，回傳 access token 與 refresh token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["TokenPairData"];
                        };
                    };
                };
                /** @description 認證失敗，統一回傳「帳號或密碼錯誤」 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 換發 access token（refresh token rotation）
         * @description 以 refresh token 換發新的 access token 與 refresh token 一對（rotation： 舊 refresh token 作廢，新 token 生效並展期）。具 reuse detection：已被 rotate 的舊 token 於寬限期（30 秒，容忍多分頁併發刷新）外再次出現，視為 token 竊取，撤銷整個 token family，後續 refresh 一律 401。refresh token 僅能放在 request body，嚴禁出現在任何 query 參數。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        refreshToken: string;
                    };
                };
            };
            responses: {
                /** @description 換發成功，回傳新的 access token 與 refresh token */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["TokenPairData"];
                        };
                    };
                };
                /** @description refresh token 無效、已過期、已撤銷或偵測到重用（reuse detection） */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 帳號登出
         * @description 登出並撤銷 refresh token：request body 帶 refreshToken 時，撤銷該 token 所屬的整個 token family（rotation 鏈），其後該 family 不可再換發。 access token 不做 blacklist，至自然到期前仍有效，前端收到 success 後自行丟棄。 不帶 body 仍回傳成功（向後相容既有前端）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        refreshToken?: string;
                    };
                };
            };
            responses: {
                /** @description 登出成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢當前登入者資訊
         * @description 以 Bearer JWT 取得當前認證主體的帳號資訊與角色，供前端在登入後補拉使用者資料。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** Format: uuid */
                                accountId: string;
                                /** @description 登入帳號 */
                                account: string;
                                /** @description 使用者姓名 */
                                name: string;
                                /**
                                 * @description 角色清單，現行值為 super_admin / coach
                                 * @example [
                                 *       "coach"
                                 *     ]
                                 */
                                roles: string[];
                            };
                        };
                    };
                };
                /** @description 未帶 token 或 token 無效/過期 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 修改或重設帳號密碼
         * @description coach 僅可修改自己的密碼，且必須提供現行密碼 oldPassword；super_admin 可重設他人密碼（免帶 oldPassword），但不得以此 API 變更自己的密碼。oldPassword 在規格上為 optional，「self 改密必填」屬 runtime 規則:coach 改自己時若未帶或帶錯 oldPassword 一律回 400 INVALID_OLD_PASSWORD。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * Format: password
                         * @description 現行密碼。coach 改自己時必填;super_admin 重設他人密碼時免填。
                         */
                        oldPassword?: string;
                        /** Format: password */
                        newPassword: string;
                    };
                };
            };
            responses: {
                /** @description 密碼修改成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                /** @description self 改密時舊密碼錯誤/未提供（errorCode：INVALID_OLD_PASSWORD） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description super_admin 不得以此 API 變更自己的密碼（errorCode：CANNOT_CHANGE_OWN_PASSWORD） */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description 輸入驗證失敗，如 newPassword 長度不符（errorCode：VALIDATION_ERROR） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢帳號列表
         * @description 取得系統內所有帳號，僅 super_admin 可操作。支援 page-based pagination。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["AccountResponse"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 建立新帳號
         * @description 僅 super_admin 可操作。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description 帳號唯一標識，即便 soft delete 後，此帳號名亦不可重複使用。 */
                        account: string;
                        /** Format: password */
                        password: string;
                        name: string;
                        /**
                         * @example [
                         *       "coach"
                         *     ]
                         */
                        roles: string[];
                    };
                };
            };
            responses: {
                /** @description 建立成功，回傳完整帳號資料 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AccountResponse"];
                        };
                    };
                };
                /** @description 帳號已存在（errorCode：ACCOUNT_ALREADY_EXISTS） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description 輸入驗證失敗，如密碼長度不符（errorCode：VALIDATION_ERROR） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢指定帳號詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AccountResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 軟刪除帳號
         * @description 僅 super_admin 可操作。限制：super_admin 不得刪除自己；亦不得刪除最後一個 active super_admin（errorCode：CANNOT_DELETE_LAST_SUPER_ADMIN，HTTP 409）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                /** @description 不得刪除最後一個 active super_admin（errorCode：CANNOT_DELETE_LAST_SUPER_ADMIN） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /**
         * 更新帳號資訊
         * @description 僅 super_admin 可更新他人資訊與角色。不得移除最後一個 active super_admin 的 super_admin 角色（errorCode：CANNOT_DOWNGRADE_LAST_SUPER_ADMIN，HTTP 409）。
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    accountId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        name?: string;
                        /**
                         * @example [
                         *       "coach"
                         *     ]
                         */
                        roles?: string[];
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["AccountResponse"];
                        };
                    };
                };
                /** @description 不得移除最後一個 active super_admin 的 super_admin 角色（errorCode：CANNOT_DOWNGRADE_LAST_SUPER_ADMIN） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/v1/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢球隊列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: (components["schemas"]["TeamResponse"] & {
                                    /**
                                     * @description 該隊未軟刪除球員數(僅列表回應提供)
                                     * @example 12
                                     */
                                    playerCount: number;
                                })[];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 建立球隊 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        teamName: string;
                    };
                };
            };
            responses: {
                /** @description 建立成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["TeamResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢指定球隊詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["TeamResponse"];
                        };
                    };
                };
                /** @description 找不到該球隊或已被刪除 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        /** 更新球隊 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        teamName: string;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["TeamResponse"];
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * 刪除球隊 (Cascade Soft Delete)
         * @description 軟刪除球隊，並連帶軟刪除旗下的 Player、Practice 與 Pitch。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    teamId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢球員列表
         * @description 取得球員列表，包含其所屬隊伍名稱。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                    /** @description 篩選指定球隊 */
                    teamId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["PlayerResponse"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /** 建立球員 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        playerName: string;
                        /** Format: uuid */
                        teamId: string;
                        jerseyNumber: number;
                        /** @description 投打慣用手描述，任意字串，長度限制 100 個繁體中文字 */
                        handedness: string;
                        /**
                         * @description 球員身高 (cm)，為九宮格分析提供 hitter_height 參數
                         * @example 175.5
                         */
                        height: number;
                        /**
                         * @description 球員體重 (kg)
                         * @example 70.2
                         */
                        weight: number;
                    };
                };
            };
            responses: {
                /** @description 建立成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PlayerResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/players/{playerId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 查詢指定球員詳情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PlayerResponse"];
                        };
                    };
                };
            };
        };
        /** 更新球員資訊 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playerId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        playerName?: string;
                        /** Format: uuid */
                        teamId?: string;
                        jerseyNumber?: number;
                        /** @description 投打慣用手描述，任意字串，長度限制 100 個繁體中文字 */
                        handedness?: string;
                        /** @description cm */
                        height?: number;
                        /** @description kg */
                        weight?: number;
                    };
                };
            };
            responses: {
                /** @description 更新成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PlayerResponse"];
                        };
                    };
                };
            };
        };
        post?: never;
        /**
         * 刪除球員 (Cascade Soft Delete)
         * @description 軟刪除球員，並連帶軟刪除該球員旗下的 Practice 與 Pitch。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    playerId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢練習列表
         * @description Page-based 分頁查詢練習列表，依建立時間新到舊排序，排除已軟刪除的練習。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["PracticeResponse"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * 新增練習
         * @description 僅能輸入練習名稱、球隊ID與球員ID。系統預設狀態為 `created`。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example 20260529 投球練習 */
                        practiceName: string;
                        /** Format: uuid */
                        teamId: string;
                        /** Format: uuid */
                        playerId: string;
                    };
                };
            };
            responses: {
                /** @description 建立成功 */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PracticeResponse"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices/{practiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 刪除練習 (Cascade Soft Delete)
         * @description 軟刪除練習，並連帶軟刪除該練習產生的所有 Pitch 資料（影片與 Raw 暫存不刪除，但不再提供觀看）。 允許刪除 `inProgress` 的練習；刪除屬資料層語意，不會呼叫外部 bt3d/bsa 服務停止擷取—— 若需停止擷取請先呼叫 `/stop` 再刪除（MVP 決定）。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    practiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                /** @description 找不到該練習或已被刪除（errorCode：PRACTICE_NOT_FOUND） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices/{practiceId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 開始練習
         * @description 將練習狀態改為 `inProgress`。
         *     後端會呼叫外部 bt3d 與 bsa 的 `/start` 端點。
         *     - 呼叫外部服務時，設有 5 秒 timeout，最多 retry 3 次。
         *     - 若任一外部服務失敗，則此 API 宣告失敗，狀態維持 `created`。
         *     - 同時間只允許有一場練習處於 `inProgress` 狀態。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    practiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 練習已成功啟動，狀態改為 inProgress */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PracticeResponse"];
                        };
                    };
                };
                /** @description 當前已有其他 inProgress 的練習（errorCode：PRACTICE_ALREADY_IN_PROGRESS）， 或練習狀態不符合啟動條件、非 created（errorCode：PRACTICE_NOT_IN_CREATED_STATE） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
                /** @description 外部 bt3d 或 bsa 服務啟動失敗 (Timeout 或呼叫失敗) */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices/{practiceId}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 結束練習
         * @description 將練習狀態改為 `ended`。
         *     後端會呼叫外部服務的 `/stop` 以停止接收感測器數據。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    practiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 練習已結束，狀態改為 ended */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PracticeResponse"];
                        };
                    };
                };
                /** @description 練習非處於 inProgress 狀態（errorCode：PRACTICE_NOT_IN_PROGRESS） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/practices/{practiceId}/pitches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢指定練習的投球列表
         * @description 回傳該練習的所有 Pitch 列表，依時間由新到舊排序。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path: {
                    practiceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["PitchSummaryResponse"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pitches/{pitchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢單球詳情
         * @description 取得指定投球的詳細 analysis 數據與影片 URL。
         *     - 影片檔(MP4) 直接由後端提供相對/絕對 URL，交由 Nginx 處理，不經由 API stream 二進位傳輸。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pitchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["PitchDetailResponse"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /**
         * 軟刪除指定單球投球資料
         * @description 單球 soft delete。被刪投球不再出現於列表、詳情、歷史查詢與 CSV 匯出。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pitchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 刪除成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
                /** @description 找不到該投球或已被刪除（errorCode：PITCH_NOT_FOUND） */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pitches/{pitchId}/favorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 收藏投球
         * @description 標註該投球為收藏。不需夾帶 practiceId。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pitchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 收藏成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pitches/{pitchId}/unfavorite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 取消收藏投球
         * @description 取消該投球的收藏。不需夾帶 practiceId。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pitchId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 取消成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/dates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢有練習的日期 (依年月)
         * @description 輸入年與月，回傳當月哪些日期有練習記錄。
         */
        get: {
            parameters: {
                query: {
                    year: number;
                    month: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/daily-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢當日練習與總投球數
         * @description 輸入日期，回傳該日期所發生的練習列表、各練習的投手/球員，以及各練習的總投球數。
         */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** Format: uuid */
                                practiceId: string;
                                practiceName: string;
                                /** Format: uuid */
                                teamId: string;
                                teamName: string;
                                /** Format: uuid */
                                playerId: string;
                                playerName: string;
                                /** @enum {string} */
                                status: "created" | "inProgress" | "ended";
                                /** @description 該場練習的總投球數 */
                                totalPitches: number;
                                /** Format: date-time */
                                createdAt: string;
                            }[];
                        };
                    };
                };
                /** @description 日期格式錯誤（FastAPI 請求驗證，errorCode：VALIDATION_ERROR） */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/daily-players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢當日有訓練的投手
         * @description 輸入日期，回傳當天有進行練習的投手(球員)清單。
         */
        get: {
            parameters: {
                query: {
                    date: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** Format: uuid */
                                playerId: string;
                                playerName: string;
                                jerseyNumber: number;
                                /** Format: uuid */
                                teamId: string;
                                teamName: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/pitches": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 歷史投球資料搜尋
         * @description 支援多條件複合篩選，取得歷史投球的列表資料（分頁）。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 球員 ID 陣列 (可選) */
                    playerIds?: string[];
                    /** @description 查詢開始日期 (可選) */
                    startDate?: string;
                    /** @description 查詢結束日期 (可選) */
                    endDate?: string;
                    /** @description 頁碼，從 1 開始 */
                    page?: components["parameters"]["pageParam"];
                    /** @description 每頁筆數，預設 20，最大限制 100 */
                    pageSize?: components["parameters"]["pageSizeParam"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PaginatedSuccessEnvelope"] & {
                            data?: {
                                items: components["schemas"]["PitchHistorySummary"][];
                            };
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/pitches/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 依搜尋條件匯出 CSV
         * @description 同步匯出符合搜尋條件的投球數據 CSV 檔。匯出列數上限為 50000;若符合條件的列數超過上限, 回 422(errorCode:EXPORT_TOO_LARGE),要求縮小日期或 playerIds 範圍,而非靜默截斷。 上限檢查在串流開始前以 count 預檢完成,故超限為 JSON 422 而非「截斷的 200」。
         */
        get: {
            parameters: {
                query?: {
                    playerIds?: string[];
                    startDate?: string;
                    endDate?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 匯出成功，同步回傳 CSV 內容 */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv; charset=utf-8": string;
                    };
                };
                /** @description 輸入不合法(playerIds 非 uuid),或符合條件的列數超過匯出上限 50000 (errorCode:EXPORT_TOO_LARGE)。為 JSON 錯誤,非截斷的 CSV。 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/exports/pitches/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 依選定投球 ID 匯出 CSV
         * @description 同步匯出選定 pitchId 清單的投球數據 CSV 檔。pitchIds 數量上限為 50000(與 search 匯出共用同一上限);超過上限回 422(errorCode:EXPORT_TOO_LARGE),非截斷的 CSV。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        pitchIds: string[];
                    };
                };
            };
            responses: {
                /** @description 匯出成功，同步回傳 CSV 內容 */
                200: {
                    headers: {
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv; charset=utf-8": string;
                    };
                };
                /** @description pitchIds 含非 uuid 值,或數量超過上限 50000(errorCode:EXPORT_TOO_LARGE)。 為 JSON 錯誤,非截斷的 CSV。 */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/streams/{streamId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢指定串流資訊
         * @description 查詢 DB 回傳 HLS playlist URLs 及當前串流狀態。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    streamId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: components["schemas"]["StreamResponse"];
                        };
                    };
                };
                /** @description 找不到該串流資源 */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 查詢相機與串流狀態列表
         * @description 回傳環境中所有設定的 Camera 狀態。
         *     - 去除 legacy deviceId 欄位。
         *     - camera id 與位置由後端從 `.env` JSON 格式(CAMERAS v2:`cameraId`/`position`/`source`)解析。
         *     - `connectionStatus` 為即時狀態:後端背景輪詢上游(bt3d/bsa `/status`+`/cameras`、
         *       recorder `/cameras`)寫入記憶體快取,本端點永遠讀快取秒回;
         *       首輪輪詢完成前一律回 `disconnected`。
         *     - 工業相機組(source 為 bt3d/bsa)額外透傳 `captureStatus`(上游原始服務狀態,
         *       debug 線索);recorder 相機與上游不可達時「省略」該欄位(不以 null 佔位)。
         *     - recorder 相機額外帶 `streamId`(該相機直播 stream 的參照 id):前端以
         *       `/cameras` 取 `streamId` → `GET /streams/{streamId}` 取 `hlsUrl` 播放,
         *       毋須(也不應)client-side 推導。bt3d/bsa 相機無直播,「省略」該欄位。
         *       `hlsUrl` 維持僅由 streams 端點提供(單一真相來源)。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 查詢成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SuccessEnvelope"] & {
                            data?: {
                                /** @example cam-01 */
                                cameraId: string;
                                /**
                                 * @description 相機架設方位
                                 * @example behind-home-plate
                                 */
                                position: string;
                                /**
                                 * @example connected
                                 * @enum {string}
                                 */
                                connectionStatus: "connected" | "disconnected" | "error";
                                /**
                                 * @description 工業相機組(bt3d/bsa)上游原始服務狀態透傳,僅該組出現;
                                 *     recorder 相機與上游不可達時省略此欄位。
                                 * @example running
                                 * @enum {string}
                                 */
                                captureStatus?: "stopped" | "starting" | "running" | "stopping" | "error";
                                /**
                                 * Format: uuid
                                 * @description recorder 相機的直播 stream 參照 id;僅 source=recorder
                                 *     相機出現(bt3d/bsa 省略,同 captureStatus 的 optional 慣例)。
                                 *     以此打 `GET /api/v1/streams/{streamId}` 取 `hlsUrl`。
                                 * @example 550e8400-e29b-41d4-a716-446655440000
                                 */
                                streamId?: string;
                            }[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * SSE 即時事件推播
         * @description 以 Server-Sent Events（`text/event-stream`）推播即時事件。
         *
         *     ### 認證
         *     原生 EventSource 無法夾帶 Authorization header，本端點改以 **`?token=<JWT>` query 參數**
         *     認證（同一 access token）。缺少或無效/過期 token 回 401。
         *     注意：token 會出現在反向代理 access log 與瀏覽器歷史，僅限短效 access token 使用。
         *
         *     ### 頻道訂閱與授權
         *     - 頻道命名：`account:{accountId}`（帳號個人頻道）、`practice:{practiceId}`（練習頻道）。
         *     - 連線**必訂自己的 `account:{accountId}` 頻道**（預設頻道，毋須指定）。
         *     - 可用 `?channels=` 以逗號分隔額外請求頻道，逐一過 RBAC 訂閱授權：
         *       `account:*` 僅允許訂自己；`practice:*` 需具 practices 讀取權限。
         *     - **無權限的頻道靜默剔除**（不擋整條連線）；實際訂閱結果以 `connected` 歡迎訊息的
         *       `data.channels` 為準。
         *
         *     ### 訊息格式
         *     每筆事件為一個 SSE `data:` 區塊，內容為 JSON 信封（見 `SseEventEnvelope`）：
         *     `{ id, type, channel, timestamp, data }`。事件類型（`type`）：
         *     - `connected`：連線歡迎訊息，`data: { "channels": [實際訂閱頻道] }`
         *     - `pitchCreated`：新投球建立，`data: { "pitchId", "practiceId" }`
         *     - `practiceAiStarted` / `practiceAiStopped`：練習 AI 採集啟動/停止，`data: { "practiceId" }`
         *
         *     ### 保活
         *     無訊息時每 **30 秒**送一行 SSE 註解 `: heartbeat` 維持連線（非 JSON 訊息，客戶端應忽略）。
         *     回應夾帶 `Cache-Control: no-cache`、`X-Accel-Buffering: no`（停用反向代理緩衝）。
         */
        get: {
            parameters: {
                query: {
                    /** @description JWT access token（取代 Authorization header） */
                    token: string;
                    /** @description 逗號分隔的額外訂閱頻道清單，例如 `practice:9a1f...,account:自己的accountId` */
                    channels?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 連線成功，開始推播事件串流（首筆為 `connected` 歡迎訊息） */
                200: {
                    headers: {
                        "Cache-Control"?: string;
                        "X-Accel-Buffering"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
                /** @description 未帶 token 或 token 無效/過期 */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErrorEnvelope"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bt3d-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 接收 bt3d 原始數據 (內網信任)
         * @description 由內網 bt3d 採集服務呼叫（v2 契約，#86，breaking：舊版毫秒整數 timestamp 格式回 422）。
         *     - 接收後端即時產生 UUID 作為 ID。
         *     - `timestamp` 為 naive 字串（UTC+8 牆鐘時間），轉為 UTC 儲存並進行 Redis 2秒配對。
         *     - 冪等重送：相同 `timestamp`（capture 時刻）視為同一顆球，回傳既有 `bt3dDataId`，
         *       不重複建立 raw 紀錄、不重複建立 pitch。
         *     - 完整原始 payload 以 JSONB 照存；裝置端附帶的舊版計算欄位（`pitch_trajectory`、
         *       `strike_zone_point`、`pitch_velocity`、`raw_traj_2d` 等）寬鬆接收、照存不拆欄。
         *     - 內網信任，不掛 JWT。
         *     - Payload 為外部 snake_case，在此處做防腐層轉換。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["Bt3dRawPayload"];
                };
            };
            responses: {
                /** @description 數據接收並持久化成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /**
                             * Format: uuid
                             * @description 後端產生的 UUID
                             */
                            bt3dDataId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bsa-data": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 接收 bsa 原始數據 (內網信任)
         * @description 由內網 bsa 採集服務呼叫（v2 契約，#86，breaking：舊版毫秒整數 timestamp 格式回 422）。
         *     - 接收後端即時產生 UUID 作為 ID。
         *     - `timestamp` 為 naive 字串（UTC+8 牆鐘時間），轉為 UTC 儲存。
         *     - 冪等重送：相同 `timestamp`（capture 時刻）視為同一顆球，回傳既有 `bsaDataId`，
         *       不重複建立 raw 紀錄。
         *     - 將原始的 `axis` 陣列拆為 `axisX`, `axisY`, `axisZ` 存入資料庫；完整原始 payload
         *       以 JSONB 照存，額外欄位寬鬆接收。
         *     - 內網信任，不掛 JWT。
         *     - Payload 為外部 snake_case，在此處做防腐層轉換。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BsaRawPayload"];
                };
            };
            responses: {
                /** @description 數據接收並持久化成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                            /**
                             * Format: uuid
                             * @description 後端產生的 UUID
                             */
                            bsaDataId: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        SuccessEnvelope: {
            /** @example true */
            success: boolean;
            /** @example 操作成功 */
            message?: string;
            /** @description 成功回應的主體。基底不限定型別，由各端點以 allOf 特化為 object 或 array （回傳陣列的端點覆寫為 array，分頁端點請改用 PaginatedSuccessEnvelope）。 */
            data: unknown;
            /** @description 其他非分頁之元數據 */
            meta?: Record<string, never>;
        };
        PaginatedSuccessEnvelope: {
            /** @example true */
            success: boolean;
            data: {
                items: Record<string, never>[];
            };
            meta: {
                pagination: {
                    /** @example 1 */
                    page: number;
                    /** @example 20 */
                    pageSize: number;
                    /** @example 150 */
                    totalItems: number;
                    /** @example 8 */
                    totalPages: number;
                };
            };
        };
        ErrorEnvelope: {
            /** @example false */
            success: boolean;
            /**
             * @description CONSTANT_CASE 錯誤碼
             * @example RESOURCE_NOT_FOUND
             */
            code: string;
            /**
             * @description 提供給使用者閱讀的錯誤訊息
             * @example 找不到指定的資源
             */
            message: string;
            /** @description 欄位層級的驗證錯誤細節 (選填) */
            errors?: {
                /** @example jerseyNumber */
                field: string;
                /** @example 必須為大於 0 的整數 */
                message: string;
            }[];
        };
        TokenPairData: {
            /**
             * @description Bearer JWT token（短效 access token）
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
             */
            accessToken: string;
            /** @example Bearer */
            tokenType: string;
            /**
             * Format: date-time
             * @description access token 到期時間
             */
            expiresAt: string;
            /** Format: uuid */
            accountId: string;
            /** @description opaque refresh token（非 JWT），僅能用於 /api/v1/auth/refresh 的 request body，嚴禁出現在任何 query 參數。 */
            refreshToken: string;
            /**
             * Format: date-time
             * @description refresh token 到期時間（rotation 時展期，sliding window）
             */
            refreshExpiresAt: string;
        };
        AccountResponse: {
            /** Format: uuid */
            accountId: string;
            /** @description 登入帳號 */
            account: string;
            /** @description 使用者姓名 */
            name: string;
            /**
             * @example [
             *       "coach"
             *     ]
             */
            roles: string[];
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        TeamResponse: {
            /** Format: uuid */
            teamId: string;
            teamName: string;
            /** @example false */
            isDeleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description 軟刪除時間，未刪除為 null
             */
            deletedAt: string | null;
            /**
             * Format: uuid
             * @description 執行軟刪除的帳號，未刪除為 null
             */
            deletedByAccountId: string | null;
        };
        PlayerResponse: {
            /** Format: uuid */
            playerId: string;
            playerName: string;
            /** Format: uuid */
            teamId: string;
            /** @description 所屬球隊名稱 */
            teamName: string;
            jerseyNumber: number;
            /** @description 投打慣用手描述，任意字串，長度限制 100 個繁體中文字 */
            handedness: string;
            /** @description cm */
            height: number;
            /** @description kg */
            weight: number;
            /** @example false */
            isDeleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description 軟刪除時間，未刪除為 null
             */
            deletedAt: string | null;
            /**
             * Format: uuid
             * @description 執行軟刪除的帳號，未刪除為 null
             */
            deletedByAccountId: string | null;
        };
        PracticeResponse: {
            /** Format: uuid */
            practiceId: string;
            practiceName: string;
            /** Format: uuid */
            teamId: string;
            /** @description 所屬球隊名稱。已軟刪除的球隊仍解析名稱（比照歷史查詢 join 語意）。 */
            teamName: string;
            /** Format: uuid */
            playerId: string;
            /** @description 球員姓名。已軟刪除的球員仍解析名稱（比照歷史查詢 join 語意）。 */
            playerName: string;
            /** @enum {string} */
            status: "created" | "inProgress" | "ended";
            /**
             * Format: date-time
             * @description 練習開始時間（/start 成功後寫入），未開始為 null
             */
            startedAt: string | null;
            /**
             * Format: date-time
             * @description 練習結束時間（/stop 成功後寫入），未結束為 null
             */
            endedAt: string | null;
            /** @example false */
            isDeleted: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * Format: date-time
             * @description 軟刪除時間，未刪除為 null
             */
            deletedAt: string | null;
            /**
             * Format: uuid
             * @description 執行軟刪除的帳號，未刪除為 null
             */
            deletedByAccountId: string | null;
        };
        PitchSummaryResponse: {
            /** Format: uuid */
            pitchId: string;
            /** Format: uuid */
            practiceId: string;
            /**
             * @description 釋放球速 (km/h)
             * @example 135.8
             */
            pitchSpeed: number | null;
            /** @example false */
            isFavorite: boolean;
            /**
             * Format: date-time
             * @description 投球時間戳記 (UTC)
             */
            timestamp: string;
        };
        PitchHistorySummary: {
            /** Format: uuid */
            pitchId: string;
            /** Format: uuid */
            practiceId: string;
            practiceName: string;
            /** Format: uuid */
            playerId: string;
            playerName: string;
            /** @description km/h */
            pitchSpeed: number | null;
            isFavorite: boolean;
            /** Format: date-time */
            timestamp: string;
        };
        PitchDetailResponse: {
            /** Format: uuid */
            pitchId: string;
            /** Format: uuid */
            practiceId: string;
            /**
             * @description 由分析產出的球種，例如 Fastball, Slider, Curveball, Changeup 等。isBt3dOnly=true（未配對）時無分析結果，為 null。
             * @example Fastball
             */
            pitchType: string | null;
            /**
             * @description 是否為未配對成功、僅有 bt3d 資料的投球
             * @example false
             */
            isBt3dOnly: boolean;
            isFavorite: boolean;
            /** Format: date-time */
            timestamp: string;
            /** @description 投球分析數據。各欄位於 isBt3dOnly=true（未配對、僅 bt3d）時無分析結果，值為 null。 */
            metrics: {
                /**
                 * @description 球速 (km/h)
                 * @example 135.8
                 */
                pitchSpeed: number | null;
                /**
                 * @description 轉速 (rpm)
                 * @example 2200
                 */
                spinRate: number | null;
                /**
                 * @description 旋轉軸 (degree)
                 * @example 215.5
                 */
                spinAxis: number | null;
                /**
                 * @description 垂直位移量 (cm)
                 * @example 45.2
                 */
                verticalBreak: number | null;
                /**
                 * @description 水平位移量 (cm)
                 * @example -25.4
                 */
                horizontalBreak: number | null;
                /**
                 * @description 進壘點 X 座標 (cm)，水平方向（3D 向量 [0]）
                 * @example 12.5
                 */
                strikeZonePointX: number | null;
                /**
                 * @description 進壘點 Y 座標 (cm)，縱深方向（3D 向量 [1]；analyze 於本壘板平面取值時可為 null）
                 * @example 0
                 */
                strikeZonePointY: number | null;
                /**
                 * @description 進壘點 Z 座標 (cm)，高度方向（3D 向量 [2]）(#86 新增)
                 * @example 75.3
                 */
                strikeZonePointZ: number | null;
                /**
                 * @description 垂直進壘角度 (degree)，負值代表向下 (#86 新增)
                 * @example -5.8
                 */
                vaa: number | null;
                /**
                 * @description 水平進壘角度 (degree) (#86 新增)
                 * @example 1.2
                 */
                haa: number | null;
                /**
                 * @description Seam-Shifted Wake 垂直分量 (cm) (#86 新增)
                 * @example 3.1
                 */
                sswVb: number | null;
                /**
                 * @description Seam-Shifted Wake 水平分量 (cm) (#86 新增)
                 * @example -1.4
                 */
                sswHb: number | null;
                /**
                 * @description 旋轉效率 (0.0–1.0) (#86 新增)
                 * @example 0.92
                 */
                spinEff: number | null;
                /**
                 * @description 有效轉速 (rpm) (#86 新增)
                 * @example 2050
                 */
                trueSpin: number | null;
                /**
                 * @description Gyro 角 (degree) (#86 新增)
                 * @example 18.5
                 */
                gyro: number | null;
            };
            media: {
                /**
                 * @description 影片非同步處理狀態 (processing:處理中, ready:已就緒, failed:失敗)
                 * @example processing
                 * @enum {string}
                 */
                videoStatus: "processing" | "ready" | "failed";
                /**
                 * Format: uri
                 * @description 前視角 MP4 影片路徑（處理中為 null，就緒後由 Nginx 服務）
                 * @example https://media.example.com/videos/practices/uuid123/front.mp4
                 */
                frontVideoUrl: string | null;
                /**
                 * Format: uri
                 * @description 側視角 MP4 影片路徑（處理中為 null，就緒後由 Nginx 服務）
                 * @example https://media.example.com/videos/practices/uuid123/side.mp4
                 */
                sideVideoUrl: string | null;
            };
            /**
             * @description 即時九宮格 (strike zone) 圖片，base64 PNG 的 data URI
             *     （`data:image/png;base64,...`，可直接放入 `<img src>`）。後端依球員身高
             *     (hitter_height) 與進壘點即時呼叫外部九宮格服務取得 (#86)。外部服務逾時/失敗、
             *     或該球尚無進壘點（無 analyze 結果）時降級為 null，不影響單球詳情其餘欄位回傳。
             * @example data:image/png;base64,iVBORw0KGgoAAAANSUhEUg...
             */
            zoneImage: string | null;
            /**
             * @description 九宮格服務的好壞球判定 (#86)。與 zoneImage 同源：外部服務逾時/失敗、或該球
             *     尚無進壘點時降級為 null。
             * @example true
             */
            isStrike: boolean | null;
        };
        StreamResponse: {
            /** Format: uuid */
            streamId: string;
            /** @example 一壘側相機直播 */
            name: string;
            /**
             * @example active
             * @enum {string}
             */
            status: "active" | "inactive" | "error";
            /**
             * Format: uri
             * @example https://stream.example.com/live/cam1/index.m3u8
             */
            hlsUrl: string;
            /** Format: date-time */
            createdAt: string;
        };
        SseEventEnvelope: {
            /**
             * @description 事件唯一識別碼（uuid hex）
             * @example 3f2a1b4c5d6e7f8090a1b2c3d4e5f607
             */
            id: string;
            /**
             * @description 事件類型，前端依此分流
             * @enum {string}
             */
            type: "connected" | "pitchCreated" | "practiceAiStarted" | "practiceAiStopped";
            /**
             * @description 來源頻道，`account:{accountId}` 或 `practice:{practiceId}`
             * @example practice:6f1d2c34-0000-0000-0000-000000000000
             */
            channel: string;
            /**
             * Format: date-time
             * @description 事件時間（UTC，秒級精度，`...Z` 結尾）
             */
            timestamp: string;
            /** @description 事件酬載（camelCase）。connected：{ channels: [...] }；pitchCreated：{ pitchId, practiceId }； practiceAiStarted / practiceAiStopped：{ practiceId }。 */
            data: Record<string, never>;
        };
        /** @description v2 契約（#86）。額外欄位（裝置端舊版計算欄位等）寬鬆接收，僅存入完整原始 payload JSONB，不拆欄。 */
        Bt3dRawPayload: {
            /**
             * @description naive datetime 字串，一律視為 UTC+8 牆鐘時間（不得帶時區 offset）， 後端轉為 UTC 儲存。支援 `T` 與空格兩種分隔、最高微秒精度。 為冪等鍵：相同 timestamp 重送視為同一顆球。bt3d 與 bsa 須使用 同一時間基準以確保 2 秒配對窗正確。
             * @example 2026-06-05T14:30:00.123456
             */
            timestamp: string;
            /**
             * @description 3D 原始軌跡點列表，每點為 `[x, y, z, t_rel]` 四元素陣列（t_rel 為相對軌跡起點的秒數）
             * @example [
             *       [
             *         0.1,
             *         18.4,
             *         1.8,
             *         0
             *       ],
             *       [
             *         0.05,
             *         14.2,
             *         1.6,
             *         0.1
             *       ]
             *     ]
             */
            raw_traj: number[][];
            /**
             * @description 軌跡起點相對時間（秒）
             * @example 0
             */
            traj_start_ts: number;
            /**
             * @description 軌跡終點相對時間（秒）
             * @example 0.46
             */
            traj_end_ts: number;
            /** @description X 軸二次擬合係數 c0（f(t) = c0 + c1*t + c2*t²；Y、Z 軸同形） */
            pitch_traj_Xc0: number;
            pitch_traj_Xc1: number;
            pitch_traj_Xc2: number;
            pitch_traj_Yc0: number;
            pitch_traj_Yc1: number;
            pitch_traj_Yc2: number;
            pitch_traj_Zc0: number;
            pitch_traj_Zc1: number;
            pitch_traj_Zc2: number;
        };
        /** @description v2 契約（#86）。額外欄位寬鬆接收，僅存入完整原始 payload JSONB，不拆欄。 */
        BsaRawPayload: {
            /**
             * @description naive datetime 字串，一律視為 UTC+8 牆鐘時間（不得帶時區 offset）， 後端轉為 UTC 儲存。支援 `T` 與空格兩種分隔、最高微秒精度。 為冪等鍵：相同 timestamp 重送視為同一顆球。須與 bt3d 使用同一時間 基準以確保 2 秒配對窗正確。
             * @example 2026-06-05 14:30:00.223456
             */
            timestamp: string;
            /**
             * @description 旋轉軸單位向量 `[x, y, z]`，後端拆解為 axisX/axisY/axisZ 儲存
             * @example [
             *       1,
             *       0,
             *       0
             *     ]
             */
            axis: number[];
            /**
             * @description 總轉速 (rpm)
             * @example 2200
             */
            rpm: number;
            /** @description 旋轉方向（時鐘表示法 + 角度） */
            spin_dir: {
                /** @example 12:00 */
                hhmm: string;
                /** @example 0 */
                degrees: number;
            };
            /** @description 旋轉傾角（時鐘表示法 + 角度） */
            spin_tilt: {
                /** @example 12:00 */
                hhmm: string;
                /** @example 0 */
                degrees: number;
            };
        };
    };
    responses: never;
    parameters: {
        /** @description 頁碼，從 1 開始 */
        pageParam: number;
        /** @description 每頁筆數，預設 20，最大限制 100 */
        pageSizeParam: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
